### ISSUE TITLE
Recent workshop video streaming

### ISSUE THREAD

**Issue by barrymay** [FrontendMasters/ios-issues#12]
## Stream recent workshop videos

The app has always allowed users to see full courses from Frontend Masters, but being able to stream recently recorded Workshop videos before they get parsed into courses would be a great value add! 

(They don't have to chunked up into sections yet, just replay what's available in the web-based video streaming)

**Comment by barrymay** [comment]
This one was done recently - I'm not sure if my suggestion had anything to do with it, but thank you!!

**Comment by dachev** [comment]
Thank you @barrymay. I forgot to close the ticket. Stay tuned for more workshop functionality.

**Comment by barrymay** [comment]
Can't wait! As always, keep up the great work!
