### ISSUE TITLE
Picture-in-picture functionality

### ISSUE THREAD

**Issue by markpinero** [FrontendMasters/ios-issues#15]
## Picture-in-picture functionality (feature request)
Allow for native iOS picture-in-picture so the video keeps playing if you switch apps.

### Preconditions

Device: iPad

### Actual and Expected Result

Expected:
Implement PIP so video can play in a corner window while you use other apps.

Actual:
If you switch apps, the video will pause.

**Comment by christopheragnus** [comment]
I second this request. This would help when taking notes using a Word processor while viewing the video.

**Comment by fmkguy** [comment]
I could totally be wrong, but didn't this use to work in the old app? Also, I third this request. I wish more apps would bring back PIP. So many used to have it... and then updated and removed it. :(

**Comment by devmrin** [comment]
4years and counting. Is there any update on this?

Thanks.

**Comment by dachev** [comment]
This is now available in v1.25.0
