### ISSUE TITLE
[UX issue] Add more granular speed options and dropdown for speed change

### ISSUE THREAD

**Issue by drIsCoding** [FrontendMasters/ios-issues#21]
## Issue Description
- Playback speed increments of .1 would be even more helpful than .2 jumps. I often watch videos at 1.1 speed.
- When switching speeds, it is inconvenient to have to cycle through all of them to get back to a slower speed. I often try out a faster speed, realize it is too fast, and want to immediately switch back to slower. It would be helpful to have a dropdown to immediately pick the slower speed instead of having to tap until I get back to it.

**Comment by dachev** [comment]
@drIsCoding We added a options menu that allows choosing an arbitrary speed without having to cycle through all the options.
