### ISSUE TITLE
[UX Issue] If video is paused, keep in paused state while switching speeds

### ISSUE THREAD

**Issue by drIsCoding** [FrontendMasters/ios-issues#28]
### Preconditions
1. iPhone 6s, but I assume happens for all devices

### Steps to Reproduce
1. Start watching a video
2. Pause
3. Tap the speed change option

### Actual and Expected Result

Expected/Desired:
Speed switches without starting to play. That way I can easily get to the desired speed without worrying about missing parts of the video while I'm in middle of switching.

Actual:
The video starts playing again

**Comment by dachev** [comment]
@drIsCoding this has been fixed in the latest release
