### ISSUE TITLE
Show Course dates

### ISSUE THREAD

**Issue by drIsCoding** [FrontendMasters/ios-issues#29]
## Issue Description
It would be helpful to have the date of the Course listed, in both the general browse Courses page and on the individual Course details page. When I'm looking for new courses to watch, I care about when it was recorded.

**Comment by ericpitcher** [comment]
I agree, I've thought about this as well, still missing in the app though :)

**Comment by dachev** [comment]
This was implemented in the latest release.

**Comment by ericpitcher** [comment]
@dachev awesome thanks!
