### ISSUE TITLE
[UX Issue] Allow Pause with no control options

### ISSUE THREAD

**Issue by jdkahn** [FrontendMasters/ios-issues#30]
## Issue Title
Want to be able to read content of video when paused

## Issue Description
When a video is paused the control options are always visible on the video and the background is dark. 

### Preconditions
```
Device: iPhone 7, iOS version 11.4.1
1. Connected to wifi
2. Logged in
```
### Steps to Reproduce
```
1. Play a video
2. Go to full screen
3. Pause the video
```
### Actual and Expected Result
```
Expected:
Able to hide the video controls to read code displayed on the screen

Actual:
Controls cannot be hidden so content is hard to read or covered by the controls
```
### Additional Information

![img_9663](https://user-images.githubusercontent.com/12548603/45336870-f2af0880-b5b7-11e8-9773-a2bd4f67a505.jpg)

**Comment by dachev** [comment]
@jdkahn This has been fixed in the live app. You should be able to download 1.0.0 from the app store.
