### ISSUE TITLE
Crash when loading video

### ISSUE THREAD

**Issue by jdkahn** [FrontendMasters/ios-issues#31]
## Issue Title
If a video is loading and you return to the previous page the app crashes

### Preconditions
```
Device: iPhone 7, iOS version 11.4.1
1. Connected to wifi
2. Logged in
```
### Steps to Reproduce
```
1. Clicked play on new video
2. Video loading icon appears
3. Click Back arrow to return to course list
```

### Actual and Expected Result
```
Expected:
To see list of courses 

Actual:
Previous page loads and then crashes
```
### Additional Information
I'm in Beijing, China. I've tried both with and without VPN and the issue is the same.

**Comment by dachev** [comment]
@jdkahn This has been fixed in the live app. You should be able to download 1.0.0 from the app store.
