### ISSUE TITLE
AppleTV Transition Between Clips Not the Same As On Mobile

### ISSUE THREAD

**Issue by pkellner** [FrontendMasters/ios-issues#32]
## AppleTV Transition Between Clips Not the Same As On Mobile

When watching any of the videos, I notice that between every clip (only while watching on AppleTV), the screen flashes back to an AppleTV default screen of some kind, then continues to the next clip.  The behavior when watching on my iphone X is a clean transition between clips with no intervening screen shot.

I recorded with my iphone a video showing this behavior here:

https://www.dropbox.com/s/1q5kq12u81o8oqu/2018-09-26%2012.06.09.mov?dl=0

**Comment by dachev** [comment]
@pkellner To the best of my knowledge this is a platform limitation. I get the same experience when I watch Youtube.
