### ISSUE TITLE
Video info text cuts off when it's too long.

### ISSUE THREAD

**Issue by 1-800-jono** [FrontendMasters/ios-issues#33]
## Issue Description
Text information beneath each video sometimes gets cut off if it's too long. I feel this is providing a bad UX because the mobile user misses important information.

I understand the inclination to have less information on a mobile device but I feel this is not a good case for it. Many of us use Frontend Masters on mobile and this creates the feeling that you're only getting part of the experience.

### Steps to Reproduce
```
Example:
1. Log in
2. Navigate to a Course
3. On some videos the information beneath it gets cut off with an "..."
```
### Actual and Expected Result

```
Expected:
Show all the text information

Actual:
Mobile user doesn't get all the necessary information on each video
```
### Additional Information
Notice the end of the text - it abruptly ends with "..."
![unnamed](https://user-images.githubusercontent.com/1545577/47922451-dfbd0400-de95-11e8-824d-a0b830fb5592.png)

**Comment by dachev** [comment]
@brentmn This is ready for testing
