### ISSUE TITLE
Suggestion: Chromecast support

### ISSUE THREAD

**Issue by 1-800-jono** [FrontendMasters/ios-issues#34]
I just wanted to suggest Chromecast support. It seems many people have/use Chromecast and this would be a great way of casting the courses to a bigger screen.

**Comment by eeston** [comment]
Also interested in this! 🙌🏻

**Comment by dachev** [comment]
@johndlopez  @johneas10 Thank you for your feedback. We've been working on Cast support but want to give it some rigorous testing before it's made available to the general public. If you are interested in getting your hands on a beta please email support@frontendmasters.com with the subject line `iOS Beta`

**Comment by 1-800-jono** [comment]
Thanks - just sent the email. Will be great to start testing it :)

**Comment by 1-800-jono** [comment]
I think the beta I received doesn't have Cast support.

**Comment by dachev** [comment]
Hey Jonathan, you are correct. We submitted the Cast build for Apple review but it's taking a little longer than expected. Stay tuned and watch for a notification from TestFlight when the new build is approved.

**Comment by dachev** [comment]
@jonathanphz The new build was approved just now. Sorry about the trouble.

**Comment by 1-800-jono** [comment]
Oh no problem at all - I'll stay tuned for the new beta update.

Thanks!

**Comment by dachev** [comment]
This was released a few weeks ago. Closing.
