### ISSUE TITLE
Support keyboard shortcuts.

### ISSUE THREAD

**Issue by Serabe** [FrontendMasters/ios-issues#36]
## Issue Description

When in an iPad with a keyboard, is pretty useful to, at least, have the following key bindings:

* Play / pause toggle with the space bar.
* 10s backward / forward with left / right arrow keys.
* Volume control with up / down arrow keys.

**Comment by r-moore** [comment]
+1 adding my vote

I actually don’t use the iOS app because of this, the website is a richer experience that lets you use spacebar to pause videos.

Would be a really nice improvement

**Comment by inudge** [comment]
+1 especially for the play/pause toggle with space bar

**Comment by aifreedom** [comment]
Just wanted to give this issue a bump and see if there's any recent update on this. It would be really nice to be able to control the video playback in the iPad app with the keyboard shortcuts.

**Comment by dachev** [comment]
@aifreedom thanks for the feedback. We'll put it on the roadmap.

**Comment by dachev** [comment]
@kenearley 1.32.0 (632)

**Comment by dachev** [comment]
Released in v1.32.0

**Comment by aifreedom** [comment]
Thank you for implementing this feature!! It’s super useful.

Just wanted to report an issue on my iPad Pro M4 with the latest FrontendMaster app. While the space key works for pausing and playing the video, the arrow keys don’t work. When holding down the command key, they do show up in the shortcut sheet. But pressing them doesn’t do anything.

Can someone take a look at it again? 🙏

**Comment by aifreedom** [comment]
Hmm, the space key just stopped working for me too. I went into the full screen mode, the space key stopped working. And exiting it didn’t make it work again.
