### ISSUE TITLE
Currently playing video is not highlighted until controls or video list is interacted with

### ISSUE THREAD

**Issue by ericpitcher** [FrontendMasters/ios-issues#37]
## Issue Description
When tapping in on a course, the last played video will start playing straight away (first video if never watched before). The active/highlight color does not show in the UI until either a video in the course list is tapped on or the previous or next video controls are tapped on, only then the active color for the currently playing video shows in the UI.

Also, another point to make, and I wrote in chat on the website about this, Chuck answered and he said he had put my message in the log for the team to see. There is only very subtle color contrast between the other videos in the list and the currently playing video, it's a slight bright gray and it's hard to notice against the otherwise white list when scrolling through, I could imagine people with color blindness problems would not even be able to see the difference. This is only for the mobile app, the web app has very good contrast between the currently playing video and the others in the video list.

### Preconditions
```
Device: iPhone 8, iOS version 13.3
1. Connected to wifi
2. Logged in
```
### Steps to Reproduce
```
1. Enter a course (for the first time or continuing an already started course).
OR
1. If you're already in a course where you have the highlighted color, go out of it and back into it.
```
### Actual and Expected Result
Expected:
For the highlighting to be there on the currently playing video.

Actual:
Not highlighted. But it can be by clicking on a video or using the previous/next video controls.

**Comment by dachev** [comment]
Hi @ericpitcher. Thanks for the feedback. We'll have those fixed in the next release.

**Comment by dachev** [comment]
@ericpitcher This should be fixed.
