### ISSUE TITLE
Bug: Lesson simultaneously playing on Chromecast and iPhone

### ISSUE THREAD

**Issue by kaizau** [FrontendMasters/ios-issues#38]
### Preconditions

iPhone 6s, iOS 13.4
Deep JS Foundations v3 - Introduction

### Steps to Reproduce

- Log in, navigate to course, cast to TV
- Lesson starts playing on chromecast
- If / when video pauses to buffer (for me, happens consistently every 10-30 seconds)
  - Press pause
  - Wait several seconds
  - Press play

### Actual and Expected Result

Expected: Playback should pause on Chromecast on first press. Then it should resume on second. Video does NOT start playing on the phone.

Actual: Both screens are paused after first press. But after second, lesson starts playing on both the phone and Chromecast.

**Comment by dachev** [comment]
@kaizau I haven't been able to reproduce this and the bug that Ken reported was something different and out of our control. So I updated the Google SDK and made a new build. Hopefully, this fixes both problems. Feel free to test with build 352.
