### ISSUE TITLE
[Crash] iOS mobile app crashes while sharing a screenshot

### ISSUE THREAD

**Issue by ishtms** [FrontendMasters/ios-issues#39]
## Issue Title
When we are in the help/support/chat screen, and try to send a screenshot/upload a file, the app crashes without any error.

### Steps to Reproduce

```
Example:
1. Log in
2. Tap on the left drawer
3. Tap the help option on the bottom
4. Start a chat and try to upload an image using the bottom image button
```
### Actual and Expected Result

```
Expected:
The image gets uploaded.

Actual:
The app crashes
```

**Comment by dachev** [comment]
@Ishtmeet-Singh Thank you for reporting this. It should be fixed now. Let us know if you are still experiencing this problem after upgrading to 1.10.1.
