### ISSUE TITLE
Video progress bar and iOS bottom bar interfere with each other

### ISSUE THREAD

**Issue by erdahuja** [FrontendMasters/ios-issues#41]
## Issue Title
Video progress bar interferes with iOS bottom bar in landscape mode 

### Preconditions
Example:
```
Device: iPhone XR, iOS version 11.0
1. Connected to wifi
2. Logged in
3. Watching any video lesson
```
### Steps to Reproduce
1.  Watch video reaches halfway
2.  Try dragging the video progress bar to forward or backward, basically do Forward or Rewind using progress bar of video. iOS bottom bar interferes with this action.

### Actual and Expected Result
Expected:
Smooth forward and rewind of videos (my be tweak progress bar design or placement a little)
### Additional Information
See, video progress bar cursor in front of my scooter (scooter for easy identification)
Screenshot:
![IMG_3812](https://user-images.githubusercontent.com/64830337/82557554-902e4e00-9b89-11ea-864a-a8215c8da6b0.JPG)

**Comment by dachev** [comment]
Thanks for reporting this @erdahuja. We'll investigate.

**Comment by dachev** [comment]
@erdahuja This has been fixed. You should be able to download 1.10.3 in the next 12 hours. Let us know if the problem persists.
