### ISSUE TITLE
Improvements for bookmarking

### ISSUE THREAD

**Issue by xtbe** [FrontendMasters/ios-issues#5]
## Make improvement for bookmarking

You can bookmark a course when you enter the course. If you just start taking the class/course, the icon is in the top description part of the class. However when you continue watching the description part isn't visible anymore and you need to scroll up to get the bookmark icon.

### Preconditions

No preconditions, just start using the application 

### Steps to Reproduce

1. Log in
2. Start taking a class and watch a video
3. Quit the class/course
4. Re-enter, the bookmark icon is more difficult to find, as you need to scroll up
  
### Actual and Expected Result

Expected:

Place the bookmark in the class/course itself, always visible so that scroll to the description is not necessary anymore. Adding a bookmark option on the course list page (overview) page would be good.
Eg add icon to top right or long tapping could bookmark it

Actual:
Bookmarking is only possible when entering the course/class. 

### Additional Information
This is more a suggestion than a bug but would be very helpful****

**Comment by dachev** [comment]
Thanks for the recommendation. This was implemented in recent updates.
