### ISSUE TITLE
Getting locked in landscape mode of app when pressing back button while viewing video in landscape mode

### ISSUE THREAD

**Issue by HishamMubarak** [FrontendMasters/ios-issues#50]
## Description
While watching a course video in landscape, press the back icon on the top left to go back. This locks the app in Landscape and orientation and goes back to the courses page. Even if we tilt the phone, the app is stuck in landscape. The only way to get out of this is to plan a video again, press the disable full screen icon and then press the back icon or restart the app.

### Preconditions
Device: iPhone 12, iOS version 14.X
1. Connected to wifi
2. Logged in

### Steps to Reproduce
Start a video
Press the Full screen icon
Press the back icon on the top left of the full screen video
And you go back to all course catalog in portrait mode

### Actual and Expected Result
When pressing the back icon, the app should go back to portrait mode

Attached a screen recording the issue.
https://user-images.githubusercontent.com/17458630/115625796-334b9280-a31a-11eb-93a3-c8bdcba71209.mp4

**Comment by dachev** [comment]
@HishamMubarak this was implemented in the latest release
