### ISSUE TITLE
Downloaded but un-started courses cannot be viewed offline.

### ISSUE THREAD

**Issue by tomacadi** [FrontendMasters/ios-issues#51]
## Issue Title
Downloaded but un-started courses cannot be viewed offline.

### Preconditions
Example:
```
Device: iPhone 11, iOS version 14.6
1. Disconnected from wifi
2. In airplane mode
2. Logged in
3. Previously downloaded a few courses but did not start them
```
### Steps to Reproduce
```
1. Logge in
2. Download a few courses but do not start them
3. Courses will appear in Offline section from hamburger menu
4. Close the app
5. turn off wifi, turn on airplane mode 
6. Try to view one of the downloaded courses
```
### Actual and Expected Result
```
Expected:
The Course would start playing since it's download and available offline.

Actual:
Message shows up: "This course is not available offline. Please connect to the internet and try again"
```
### Additional Information
Discovered this issue while on a long flight. As you can imagine, there was no internet to connect to so I could not view any of the downloaded  courses.

@brentmn

Although I am quite certain that I had already opened some of the offline courses - none of them worked for me. While trying to reproduce the issue, I did notice that some courses started to work, specifically if I started them just before turning off wifi and turning on airplane mode.

**Comment by dachev** [comment]
Thanks for the report @tomacadi. We are investigating.

**Comment by dachev** [comment]
@tomacadi Can you take a look at this screen recording? Did I get the steps right or am I doing something different?


https://user-images.githubusercontent.com/66780/120926392-d90a6380-c706-11eb-8fbb-922b8ecb13b6.MP4

**Comment by tomacadi** [comment]
Some notes:
It looks like the course that you are testing on had already been downloaded and probably played before.

In my case:
I downloaded the entire **course** - all sections for the first time (I only streamed them before).
I only tried to press play on the course after being in airplane mode with no wifi to connect to.

**Comment by dachev** [comment]
It looks like this is happening because new courses don't have a session, we fail to populate the local cache, and when we return to the screen in offline mode the missing session looks like a failure.

**Comment by dachev** [comment]
@tomacadi I think this is fixed in the latest release. Do you mind taking a look when you have a chance?

**Comment by robbie-hinman** [comment]
I am experiencing this still.

**Comment by dachev** [comment]
@robbie-hinman thank you for a heads up. Would you be able to record a screencast demonstrating the problem. It's going to help us a lot debugging the issue.

**Comment by robbie-hinman** [comment]
Here you are: 

https://github.com/user-attachments/assets/b78b34d4-6734-41cb-9691-dcb835e0cabf

**Comment by dachev** [comment]
@robbie-hinman it looks like the lesson hadn't actually download. This is what it looks like when it is. The is a point to be made though that the UI can probably use some improvement to avoid confusion.

https://github.com/user-attachments/assets/a039f1db-42ad-4530-b4ad-7447cd31a4f7
