### ISSUE TITLE
video not playing on iPad

### ISSUE THREAD

**Issue by adardesign** [FrontendMasters/ios-issues#52]
The video player freezes and doesn't play new videos

Device: iPad 
1. Connected to wifi
2. Logged in
3. says 00000 and remains like this

![image](https://user-images.githubusercontent.com/23543/120673787-7e041280-c461-11eb-835c-6741f18632ac.png)

**Comment by dachev** [comment]
@adardesign Thank you for the report. Is this happening with the latest app release (1.17.6)?

**Comment by adardesign** [comment]
Yes

**Comment by dachev** [comment]
@adardesign we made some player changes that should hopefully fix this. Can you try the latest release?

**Comment by olehlutsenko** [comment]
Same issue as describe above, which I have noticed I experience from recently?.. Not sure when exactly it has started, I haven't seen this issue before, until maybe last week?..

Device: iPhone 11 IOS 15.1 (first noticed before update when on IOS 14.8)
App Version: 1.20.2

The important detail that it happens to me only when I am on cellular network (I have 4G). I have "Download over cellular network" flag is on, but that doesn't matter. 

Steps to reproduce: 
- Disable WiFi
- Try to play video. it will stay at 00:00:00

After enabling WiFI video loads normally. Disabling WiFi when the video started playing will continue to play video for a bit, until cache is runs out? Clicking any controls, like trying to open another video, jump forward or backward, the video player is unresponsive. 

Rest of the app seems to work fine.

**Comment by dachev** [comment]
@olehlutsenko Thank you for the information. It was really helpful. We have a fix on the way but it may take a few extra days for Apple to approve due to the holidays. Keep an eye out for v1.20.4

**Comment by olehlutsenko** [comment]
Thank you @dachev, I will try ver. 1.20.4 and will report here

**Comment by adardesign** [comment]
Thanks

**Comment by olehlutsenko** [comment]
@dachev I have tried version 1.20.4 and issue seems to be fixed! Thank you very much!

**Comment by dachev** [comment]
@olehlutsenko @adardesign Happy to help. Thank you for your patience.
