### ISSUE TITLE
Rendering raw markdown

### ISSUE THREAD

**Issue by akulsr0** [FrontendMasters/ios-issues#53]
## Markdown not displaying properly

If Instructor's card in upcoming workshop contains link, it's not rendering properly.

### Preconditions
Example:
```
Device: iPhone 8, iOS version 14.4.2
1. Connected to wifi
2. Logged in
```
### Steps to Reproduce

```
Example:
1. App Open 
2. Navigate to Workshops (Upcoming)
3. Open any workshop whose Instructor Information Card has link
```
### Actual and Expected Result
To make sure we're all on the same page, it helps if you let us know what you were expecting.
Example:
```
Expected:
Render hyperlinks through which user can easily open them

Actual:
Renders raw markdown
```
### Additional Information
![image0](https://user-images.githubusercontent.com/43666833/125830688-f2eaae3b-eb7c-48b8-a62a-72561e2fb1e0.png)

**Comment by dachev** [comment]
@akulsr0 Thanks for the heads up. We'll fix that in the next release.

**Comment by dachev** [comment]
@akulsr0 this should be fixed in the latest release.
