### ISSUE TITLE
Allow iOS to auto-lock/sleep when paused

### ISSUE THREAD

**Issue by ghost** [FrontendMasters/ios-issues#55]
## Issue Description

When you pause a video on the Frontend Masters ios app and walk away, the app doesn’t honor the iPad’s auto-lock settings . It would be better for battery life and for the security of our devices if the *paused* player would honor the auto-lock feature from the iPad’s settings.

### Preconditions

```
Device: iPad Air 4/iPhone se 2020, iOS version 14
```
### Steps to Reproduce
The most import part.
```
1. Start a video in FEM
2. Pause it
3. Walk away for a few hours
```
### Actual and Expected Result
```
Expected:
The iOS device should be locked and sleeping.

Actual:
The iOS device is awake and still paused on FEM video.
```
### Additional Information

Thank you!

**Comment by dachev** [comment]
@lineus Did you close this because you changed your mind or because it's no longer an issue? It sounds like a valid concern and I was going to address it soon.

**Comment by ghost** [comment]
I have no idea how I did that ;)

**Comment by dachev** [comment]
@lineus this should be fixed in the latest release
