### ISSUE TITLE
add Siri commands for pause/play seek-forward, seek-back, next chapter, previous chapter

### ISSUE THREAD

**Issue by chucksteinmn** [FrontendMasters/ios-issues#56]
## Issue Title
Be as descriptive as possible when creating the issue title.

Less helpful:
> Can't watch video!

More helpful:
> The video player freezes after pausing a downloaded lesson

### Preconditions
Example:
```
Device: iPhone X, iOS version 11.0
1. Connected to wifi
2. Logged in
3. Previously had watched first two lessons of the course, "Fundamentals to Functional."
```
### Steps to Reproduce
The most import part.
```
Example:
1. Log in
2. Navigate to Courses Index
3. Tap "Fundamentals to Functional" Course
```
### Actual and Expected Result
To make sure we're all on the same page, it helps if you let us know what you were expecting.
Example:
```
Expected:
The Course would start playing at third lesson

Actual:
The Course started playing at first lesson
```
### Additional Information
Add any other information you think will be helpful. Screenshots are great!

**Comment by dachev** [comment]
Closing due to lack of details. The description is just the new issue template. Please create a valid issue by providing more details.
