### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by chucksteinmn** [FrontendMasters/ios-issues#57]
## Issue Title
Be as descriptive as possible when creating the issue title.

* the progress (which videos I already consumed) is not always properly synced between the web and the iOS apps. I watch the videos on my laptop, but also on my phone and iPad. And when I switch to the iOS app, the app "thinks" I'm still on the last video from yesterday. It would be nice that it retrieves the progress everytime the app is activated, so that I'm not forced to exit the app and open it again

https://app.intercom.com/a/apps/w1ukcwje/inbox/inbox/58955/conversations/12149500102129

**Comment by dachev** [comment]
@chucksteinmn One bug per issue please.
