### ISSUE TITLE
Full screen mode bugs, iPhone

### ISSUE THREAD

**Issue by hichammounadi** [FrontendMasters/ios-issues#60]
Device : iPhone 13 pro 📱 
Issue: when you try to make the mode of the video **full screen** the full screen icon doesn't work, the work around solution was to turn off the **portrait orientation lock** and orient the phone, same issue when you want to exit the full screen mode

**Comment by dachev** [comment]
@hichammounadi thank you for the heads up. We are working on it and we'll release a fix soon.

**Comment by hichammounadi** [comment]
It works smoothly, thank you
