### ISSUE TITLE
Fix download progress text color in dark mode

### ISSUE THREAD

**Issue by dachev** [FrontendMasters/ios-issues#61]
Title says it all

<img width="414" alt="image" src="https://user-images.githubusercontent.com/66780/216104776-f0572864-2037-4f4d-810c-857860b5b726.png">

**Comment by dachev** [comment]
@kenearley 1.26.0 (574)

**Comment by kenearley** [comment]
Looks good 🎉

**Comment by dachev** [comment]
Released in v1.26.0
