### ISSUE TITLE
Need `zoomed-to-fill` option in the app or even zoom percentage

### ISSUE THREAD

**Issue by PerpetualWar** [FrontendMasters/ios-issues#62]
Device: iPhone 13 Pro Max, iOS version 16.1
Device: Samsung Galaxy Tab S6 Lite, Android version 12

Both iOS and Android apps are missing this same feature: `zoomed-to-fill` (YouTube calls it like this).

Basically depending on the device screen size, we have black bars either on top/bottom or left/right. 

It would be nice to be able to `zoom` to not have black borders anymore, even if it means cutting off from other axis' sides.

Even better would be having custom zoom implemented (being able to zoom to specific portion of the video), but at least `zoomed-to-fill` feels necessary for any modern video app.

**Comment by dachev** [comment]
Pinch-zoom delivered in v1.27.0
