### ISSUE TITLE
Allow Continuous Playback Upon Entering Background

### ISSUE THREAD

**Issue by leocaseiro** [FrontendMasters/ios-issues#63]
I normally watch the videos while I'm commuting to work, however, sometimes I need to put my phone on my pocket, or I reply messages, and I change apps, so I would like to avoid the video to stop.

Can you please enable the feature to keep the video playing in the background while I can still listen to the video?

I believe this is the feature on iOS and this is how enable it:

https://developer.apple.com/documentation/avfoundation/media_playback/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

Thank you so much!

--

Updated Sep 23rd 2023
The first link I posted is now broken. Maybe these links help:

https://developer.apple.com/library/archive/qa/qa1626/_index.html

https://www.kodeco.com/34269507-background-modes-tutorial-getting-started

https://stackoverflow.com/questions/10429204/how-to-handle-background-audio-playing-while-ios-device-is-locked-or-on-another

**Comment by dachev** [comment]
@leocaseiro when you close the app you should be able to resume playback from the lock screen or mission control. Also, in the latest version of the app you should be able to use picture-in-picture.

**Comment by leocaseiro** [comment]
Thank you for your suggestion.

I am aware of that, but is not super convenient. 

It would be nice if this worked automatically.

**Comment by leocaseiro** [comment]
Picture in Picture also stops the audio when the phone is locked.

--
Updated Sep 23rd 2023
The audio keeps playing only when in Picture in Picture mode on Lock Screen. It pauses if is full screen.

**Comment by leocaseiro** [comment]
I receive a newsletter that multiple iOS features were added to the app, did by any chance, the background audio was added?

They mentioned about Picture in Picture, but that feature was added a while back.

**Comment by dachev** [comment]
@leocaseiro Can you take a look at this video and tell me if this is what you want because I can listen to the audio when I lock my screen.

https://github.com/FrontendMasters/ios-issues/assets/66780/99fe8ac9-d50f-4b0c-b963-7ff08c1fbf52

**Comment by leocaseiro** [comment]
Hi @dachev, this is exactly what I want, but it doesn't work for me. It keeps pausing every time I lock the screen.

**Comment by dachev** [comment]
@leocaseiro does it pause immediately after you go to the lock screen or does it take a few seconds?

**Comment by leocaseiro** [comment]
Hi @dachev, I don't know how you were able to record when you lock your screen. I was going to show you that the sound is locked as soon as we lock the screen.

I noticed that the video/audio keeps playing in background, if I have the player in Picture in Picture mode, but it pauses when is in full screen or just on the top view (with Notes access)

**Comment by leocaseiro** [comment]
Analysing your screen recording, I realised that your screen is not locking, it's just showing the notifications screen (slide from top to down on iPhone 10+).

That works the same way you demonstrated on your screen recording. Can you please test using the Lock Screen mode? That will pause the video. Just like if you watch this video you posted on the iOS GitHub app.

**Comment by dachev** [comment]
@leocaseiro are you seeing something similar on your phone?

https://github.com/FrontendMasters/ios-issues/assets/66780/8d8f3518-0af7-4633-9296-a65d49dd5ad5

**Comment by leocaseiro** [comment]
Hi @dachev, exactly same behaviour. It pauses the video when locking the screen.

**Comment by leocaseiro** [comment]
The feature I've requested, is to keep the video playing when you lock your screen. Something that youtube has, and some others players too (VLC, nPLayer, etc). 

Are you using `AVAudioSessionCategoryAmbient` or `AVAudioSessionCategoryPlayback`?

https://itecnote.com/tecnote/swift-avfoundation-playing-audio-in-background-on-lock-screen-in-swift/

I attached an example here from youtube app: 

https://github.com/FrontendMasters/ios-issues/assets/940070/330b0617-d50a-44ff-bbf6-9d3f79253361

**Comment by dachev** [comment]
@leocaseiro both approaches have their own strengths and weaknesses and there is no universally accepted behavior among all apps (e.g. Safari). Personally I prefer being on the safe side and pausing playback when I lock my device because I expect privacy and silence. Resuming the player is easy enough that this is almost a non-issue when I want to continue listening. I'll bring it up with the team and if they favor uninterrupted playback we'll add it to the next release.

**Comment by leocaseiro** [comment]
Hi @dachev I understand that. 
However, this could be a feature that users could opt-in.

VLC, for example has an option to ask if user wants to keep playing.

I'm asking for that feature. I don't intend to change the default behaviour.

![image](https://github.com/FrontendMasters/ios-issues/assets/940070/c0876a31-e198-4429-a574-bd3670e04f58)

**Comment by dachev** [comment]
@leocaseiro this is now live (version 1.29.0). Thanks for your feedback and let us know if you have any suggestion or comments.

**Comment by leocaseiro** [comment]
Thank you, thank you so much! I really appreciate!!!
