### ISSUE TITLE
Videos won't play after app was in background once

### ISSUE THREAD

**Issue by kvndrsslr** [FrontendMasters/ios-issues#64]
### Preconditions

Device: iPhone Xs (iOS 16.0)
1. Connected to wifi
2. Logged in

### Steps to Reproduce

1. Play a video
2. Pause the video
3. Press iPhone power button or switch to another app for a couple of minutes
4. Back to FrontendMasters, the video timeline shows 0:00/0:00 and no video will play
5. Only quitting the app, waiting for iOS to actually terminate it and then relaunching it results in the ability to play videos being restored properly

### Actual and Expected Result
To make sure we're all on the same page, it helps if you let us know what you were expecting.

Expected:
Videos can play after the app being in the background / the device being locked for some time

Actual:
Videos don't play

--- 
**Edit:** Forgot to mention that it also happens on my iPad. So I'm surprised to not find this issue here already since it doesn't seem to be a device issue.

**Comment by dachev** [comment]
@kvndrsslr we are aware of this bug and working to fix it soon.

**Comment by dachev** [comment]
@kvndrsslr We pushed a new release. Keep an eye for 1.25.2 and let us know if the problem persists.
