### ISSUE TITLE
Pause button mutes video, does not pause

### ISSUE THREAD

**Issue by wrekone** [FrontendMasters/ios-issues#68]
### Preconditions
Device: iPad (6th generation)
iPadOS Version: 17.0.2 (21A351)

### Steps to Reproduce
1. Play any video in any course
2. Tap the on-screen pause button
3. Observe that video continues playing, but is now muted

### Actual and Expected Result
Expected:
Video pauses when the on-screen pause button is tapped.

Actual:
Video does not pause. Video is muted.

### Additional Information
* This is reproducible when streaming on WiFi and when viewing downloaded content.
* Video will **unmute** if 10-second seek button is tapped or if timeline bar is used to manually select a different point in the video.

**Comment by dachev** [comment]
This one was fixed a while ago but Apple is still holding the release.

**Comment by dachev** [comment]
This is now released and available for download from the app store.
